### ISSUE TITLE
Errors when migrating to django 1.7

### ISSUE THREAD

**Issue by tttomekkk** [edoburu/django-fluent-contents#38]
When migrating from 1.6 to 1.7 I hit such errors. All generated calling `manage.py validate`.

1)
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/apps/config.py", line 197, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/fluent_contents/models/__init__.py", line 23, in <module>
    from fluent_contents.models.fields import PlaceholderField, PlaceholderRelation, ContentItemRelation
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/fluent_contents/models/fields.py", line 2, in <module>
    from django.contrib.contenttypes.generic import GenericRelation, GenericRel
ImportError: cannot import name GenericRel
```
According to [django 1.7 release notes](https://docs.djangoproject.com/en/dev/releases/1.7/#reorganization-of-django-contrib-contenttypes) some changes were applied to  content types application. 

Digging a bit, it looks like although `GenericRelation` class was moved, some steps were made to sustain possibility of importing it the old way. `GenericRel` wasn't treated that way and **can't be imported** from `django.contrib.contenttypes.generic` anymore.

2)
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/fluent_pages/pagetypes/fluentpage/admin.py", line 6, in <module>
    from fluent_contents.analyzer import get_template_placeholder_data
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/fluent_contents/analyzer.py", line 4, in <module>
    from template_analyzer.djangoanalyzer import get_node_instances
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/template_analyzer/__init__.py", line 1, in <module>
    from .djangoanalyzer import get_node_instances
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/template_analyzer/djangoanalyzer.py", line 11, in <module>
    from django.template.loader_tags import ConstantIncludeNode, ExtendsNode, BlockNode
ImportError: cannot import name ConstantIncludeNode
```

Looks like ConstantIncludeNode (and its base class BaseIncludeNode) was removed, I can't find them anywhere in Django code.

3)
```
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f44e830a1b8>
Traceback (most recent call last):
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 222, in wrapper
    fn(*args, **kwargs)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 105, in inner_run
    self.validate(display_num_errors=True)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 362, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/home/tomek/htdocs/isivi/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 414, in check
    raise CommandError(msg)
django.core.management.base.CommandError: System check identified some issues:

ERRORS:
<class 'fluent_pages.admin.pageadmin.DefaultPageParentAdmin'>: (admin.E016) The value of 'form' must inherit from 'BaseModelForm'.
```

Django 1.7 came with some new [project check framework](https://github.com/django/django/blob/master/docs/ref/checks.txt) and some code breaks one of this spec rules.

BTW
Thx a lot for nice group of *fluent* apps!

**Comment by vdboor** [comment]
This is all solved with the recent commits.
